apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: cloud1-region1-child1
  namespace: k0rdent
  labels:
    kof: collector
spec:
  template: aws-standalone-cp-0-0-5
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: k0rdent
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-west-2
    worker:
      instanceType: t3.small
    workersNumber: 3
    clusterLabels:
      k0rdent.mirantis.com/kof-storage-secrets: "true"
  serviceSpec:
    priority: 100
    services:
      - name: cert-manager
        namespace: kof
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true
      - name: kof-operators
        namespace: kof
        template: kof-operators-0-1-1
      - name: kof-collectors
        namespace: kof
        template: kof-collectors-0-1-1
        values: |
          global:
            clusterName: cloud1-region1-child1
          opencost:
            enabled: true
            opencost:
              prometheus:
                username_key: username
                password_key: password
                existingSecretName: storage-vmuser-credentials
                external:
                  url: https://vmauth.cloud1-region1.kof.mirantisdemo.com/vm/select/0/prometheus
              exporter:
                defaultClusterId: cloud1-region1-child1
          kof:
            logs:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: https://vmauth.cloud1-region1.kof.mirantisdemo.com/vls/insert/opentelemetry/v1/logs
            metrics:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: https://vmauth.cloud1-region1.kof.mirantisdemo.com/vm/insert/0/prometheus/api/v1/write
