apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: ${NAMESPACE}-azure-${CLUSTERNAME}${UNIQUE_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: azure-standalone-cp-0-2-0
  credential: azure-cluster-identity-cred
  config:
    clusterLabels:
      k0rdent: demo
    location: "eastus"
    controlPlaneNumber: 1
    workersNumber: 1    
    subscriptionID: ${AZURE_SUBSCRIPTION_ID} 
    controlPlane:
      vmSize: Standard_NV4as_v4
    worker:
      vmSize: Standard_NV4as_v4
