apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: ${NAMESPACE}-aws-${CLUSTERNAME}${UNIQUE_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: aws-standalone-cp-0-2-0
  credential: aws-cluster-identity-cred
  config:
    region: ${AWS_REGION}
    clusterLabels:
      k0rdent: demo
    controlPlaneNumber: 1
    workersNumber: 2
    controlPlane:
      instanceType: t3.small
    worker:
      instanceType: t3.small
