apiVersion: v1
kind: Secret
metadata:
  name: gcp-cloud-sa
  namespace: ${TESTING_NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
data:
  credentials: ${GCP_CREDENTIAL}
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: gcp-credential
  namespace: ${TESTING_NAMESPACE}
spec:
  identityRef:
    apiVersion: v1
    kind: Secret
    name: gcp-cloud-sa
    namespace: ${TESTING_NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-cloud-sa-resource-template
  namespace: ${TESTING_NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
data:
  configmap.yaml: |
    {{- $secret := (getResource "InfrastructureProviderIdentity") -}}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: gcp-cloud-sa
      namespace: kube-system
    type: Opaque
    data:
      cloud-sa.json: {{ index $$secret "data" "credentials" }}